version: "3.9"
services:
  insurance-policies-service:
    container_name: insurance-policies-service
    image: insurance-policies-service
    build:
      context: .
      dockerfile: .dockerfile
    ports:
      - "8050:8050"
    environment:
      - SPRING_APPLICATION_NAME=msvc-insurance-policies
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://testuao.postgres.database.azure.com:5432/postgres?user=jacfdev&password={test123*}&sslmode=require
      - SPRING_DATASOURCE_USERNAME=jacfdev
      - SPRING_DATASOURCE_PASSWORD=test123*
      - SPRING_JPA_HIBERNATE_DDLAUTO=update
      - SPRING_JPA_DATABASE=postgresql
      - SPRING_JPA_DATABASEPLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_CONFIG_IMPORT=optional:configserver:http://host.docker.internal:8888
      - EUREKA_INSTANCE_HOSTNAME=host.docker.internal
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://host.docker.internal:8761/eureka/
